language: C++

matrix:
  include:
    - os: osx
    - os: linux
      dist: trusty
      compiler: clang-3.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.8

script:
  - make
  
